# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SampleExtractor
                                 A QGIS plugin
 A plugin to extract samples from crop images using SOM and Hierarquical clustering
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-27
        copyright            : (C) 2026 by Abner Anjos
        email                : abner.anjos@inpe.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SampleExtractor class from file SampleExtractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sample_extractor import SampleExtractor
    return SampleExtractor(iface)
